$ANSIBLE_VAULT;1.1;AES256
30323762353036393865343838346538643937383031303766636532373561396538333732363834
3638303032313032336331303533643333623732643130650a376130623038363138306239396132
31383436333234633238656164346537316434303231323532656138663266346364643265626136
3065356135616136650a646332623537343639383061373363363463393363613939363235656331
65393036343735646561363139396437323131643430336566346639333966623934313031663562
37636637346638643939383033346137333838643738323865313238343761353235643466343130
33643432316536393965376234373038666462303262326230316536316565316333383333646336
39326635386365653730323738646136323030306166353337623339393431653864656366343062
64333664313634346439346263363935323961386232336335616634613537333034663534663661
62363663353663363933616439366163343933386466636235623035653933363234623739653036
633231616463333639623130663838666462
