$ANSIBLE_VAULT;1.1;AES256
32653338623338353137353730343561653261613038353964333535666366656263336465303734
3135373630356563613535376162643034636165343161330a366162373262626565356539626132
63323861336166613762363338646433376265333066653736386139636462613532356635633639
3831383139396334620a306565373833623335373938626163656166383137666632663564373163
33393565363036643434663637316434306338653330343639656661383234666366623963653239
63343136356264346366393465623164623633343433393764623564326166343264356365633631
63343037303635393165323634636635333764313639653564343966666134626631363563373233
38356534336338653330643039356263663132393630636264396135356638373237313530336137
39636534373662393461613835396331656338343363383633396361356539353134393265633265
31316331303833633034636661306634386261616662363030346339626235613734356465393235
626334393637333635616539633539383531
