---
# tasks file for roles/mysql
---
- name: Installer MySQL et dépendances
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Démarrer et activer MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Créer la base de données de l'application
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sockz

- name: Créer l'utilisateur MySQL "db_user"
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
