$ANSIBLE_VAULT;1.1;AES256
61383338643930316461383562306130373165613231313861376261373834666465613437653735
3563613931333937626465313931373639633937316163390a366235633965653063346632313463
63373664373966353763646437373138663434343538303763333130376432653261346133303931
6262636134323931650a313730633235623565313865353031663138656137303835653163613761
33646662323433383632326564623333663462356666383635633333643861666330313637333239
39353364313030333966613062613635383031383738316335633832333233613732666539313932
38343836363563346633353639386234663239343539626631303434376337626232653438303636
39623033316361646630383265323262636461316564653739643464633237656333643736383466
62353231643266623161376565663830303666363362313136383032626234386537613531663633
39343766653063653231666631383539356539333935643336643663396366623063613632663337
613733623763626161383030663433646430
